[package]
name = "ac-dat"
description = "Reader for Turbine DAT archives (client_portal.dat, client_cell_1.dat)"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
memmap2.workspace = true
thiserror.workspace = true

[dev-dependencies]
sha2.workspace = true
hex.workspace = true
